### ISSUE TITLE
Crash when started in flight mode

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#103]
STR:
0. Enable flight mode.
1. Start easy xkcd from the widget.
2. As you have no connection choose "show favorites".
3. Press back button. (Hardware key here)

What happens: crashes and closes app.
What should happen: only close app

Logcat:

```
I/ActivityManager(  651): START u0 {act=de.tap.easy_xkcd.ACTION_COMIC flg=0x10000000 cmp=de.tap.easy_xkcd/.Activities.MainActivity bnds=[36,200][1044,1203] (has extras)} from uid 10248 on display 0
I/ActivityManager(  651): Start proc 16954:de.tap.easy_xkcd/u0a248 for activity de.tap.easy_xkcd/.Activities.MainActivity
E/AndroidRuntime(16954): Process: de.tap.easy_xkcd, PID: 16954
E/AndroidRuntime(16954): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.tap.easy_xkcd.fragments.comics.ComicFragment.zoomReset()' on a null object reference
E/AndroidRuntime(16954):    at de.tap.easy_xkcd.Activities.MainActivity.onBackPressed(MainActivity.java:728)
W/ActivityManager(  651):   Force finishing activity de.tap.easy_xkcd/.Activities.MainActivity
W/ActivityManager(  651): Activity pause timeout for ActivityRecord{aa719c0 u0 de.tap.easy_xkcd/.Activities.MainActivity t9814 f}
I/WindowState(  651): WIN DEATH: Window{98771ab u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}
I/ActivityManager(  651): Process de.tap.easy_xkcd (pid 16954) has died
I/ActivityManager(  651): START u0 {act=de.tap.easy_xkcd.ACTION_COMIC flg=0x10000000 cmp=de.tap.easy_xkcd/.Activities.MainActivity bnds=[36,200][1044,1203] (has extras)} from uid 10248 on display 0
I/ActivityManager(  651): Start proc 17063:de.tap.easy_xkcd/u0a248 for activity de.tap.easy_xkcd/.Activities.MainActivity
E/AndroidRuntime(17063): Process: de.tap.easy_xkcd, PID: 17063
E/AndroidRuntime(17063): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.tap.easy_xkcd.fragments.comics.ComicFragment.zoomReset()' on a null object reference
E/AndroidRuntime(17063):    at de.tap.easy_xkcd.Activities.MainActivity.onBackPressed(MainActivity.java:728)
W/ActivityManager(  651):   Force finishing activity de.tap.easy_xkcd/.Activities.MainActivity
W/ActivityManager(  651): Activity pause timeout for ActivityRecord{124ff4f u0 de.tap.easy_xkcd/.Activities.MainActivity t9815 f}
I/WindowState(  651): WIN DEATH: Window{f8e9336 u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}
I/ActivityManager(  651): Process de.tap.easy_xkcd (pid 17063) has died
I/ActivityManager(  651): Start proc 20450:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  651): Killing 20450:de.tap.easy_xkcd/u0a248 (adj 15): empty for 1957s
I/ActivityManager(  651): Start proc 21697:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  651): Killing 21697:de.tap.easy_xkcd/u0a248 (adj 15): empty for 3801s
I/ActivityManager(  651): Start proc 24011:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  651): Killing 24011:de.tap.easy_xkcd/u0a248 (adj 15): empty for 1800s
I/ActivityManager(  651): START u0 {act=de.tap.easy_xkcd.ACTION_COMIC flg=0x10000000 cmp=de.tap.easy_xkcd/.Activities.MainActivity bnds=[36,200][1044,1203] (has extras)} from uid 10248 on display 0
I/ActivityManager(  651): Start proc 26260:de.tap.easy_xkcd/u0a248 for activity de.tap.easy_xkcd/.Activities.MainActivity
W/XPrivacy(26260): Hooking package=de.tap.easy_xkcd
W/System.err(26260):    at de.tap.easy_xkcd.Activities.MainActivity.onResume(MainActivity.java:772)
I/ActivityManager(  651): Displayed de.tap.easy_xkcd/.Activities.MainActivity: +1s940ms
E/MessageQueue-JNI(26260): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.tap.easy_xkcd.fragments.comics.ComicFragment.zoomReset()' on a null object reference
E/MessageQueue-JNI(26260):  at de.tap.easy_xkcd.Activities.MainActivity.onBackPressed(MainActivity.java:728)
E/AndroidRuntime(26260): Process: de.tap.easy_xkcd, PID: 26260
E/AndroidRuntime(26260): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.tap.easy_xkcd.fragments.comics.ComicFragment.zoomReset()' on a null object reference
E/AndroidRuntime(26260):    at de.tap.easy_xkcd.Activities.MainActivity.onBackPressed(MainActivity.java:728)
W/ActivityManager(  651):   Force finishing activity de.tap.easy_xkcd/.Activities.MainActivity
W/ActivityManager(  651): Activity pause timeout for ActivityRecord{53e7d5c u0 de.tap.easy_xkcd/.Activities.MainActivity t9820 f}
I/WindowState(  651): WIN DEATH: Window{7b792b7 u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}
I/ActivityManager(  651): Process de.tap.easy_xkcd (pid 26260) has died
```

CM13

**Comment by T-Rex96** [comment]
Fixed in the latest update
