### ISSUE TITLE
Crashes always when accessed from widget

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#98]
Reproducible: Always

Logcat:
```
E/AndroidRuntime(17298): Process: de.tap.easy_xkcd, PID: 17298
E/AndroidRuntime(17298): java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.design.widget.FloatingActionButton de.tap.easy_xkcd.Activities.MainActivity.getFab()' on a null object reference
E/AndroidRuntime(17298): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment.onPrepareOptionsMenu(ComicFragment.java:572)
E/AndroidRuntime(16522): Process: de.tap.easy_xkcd, PID: 16522
E/AndroidRuntime(16522): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment$ComicAdapter.<init>(ComicFragment.java:133)
E/AndroidRuntime(16522): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$ComicBrowserPagerAdapter.<init>(ComicBrowserFragment.java:193)
E/AndroidRuntime(16522): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPostExecute(ComicBrowserFragment.java:167)
E/AndroidRuntime(16522): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPostExecute(ComicBrowserFragment.java:125)
I/ActivityManager(  619): Start proc 10553:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  619): Process de.tap.easy_xkcd (pid 10553) has died
I/ActivityManager(  619): Start proc 17341:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  619): Process de.tap.easy_xkcd (pid 17341) has died
I/ActivityManager(  619): START u0 {act=de.tap.easy_xkcd.ACTION_COMIC flg=0x10000000 cmp=de.tap.easy_xkcd/.Activities.MainActivity bnds=[36,200][1044,1203] (has extras)} from uid 10248 on display 0
I/ActivityManager(  619): Start proc 21711:de.tap.easy_xkcd/u0a248 for activity de.tap.easy_xkcd/.Activities.MainActivity
W/XPrivacy(21711): Hooking package=de.tap.easy_xkcd
E/WindowManager(21711): android.view.WindowLeaked: Activity de.tap.easy_xkcd.Activities.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{5c08c23 V.E...... R.....ID 0,0-1026,488} that was originally added here
E/WindowManager(21711): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPreExecute(ComicBrowserFragment.java:141)
E/WindowManager(21711): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment.onCreateView(ComicBrowserFragment.java:90)
E/WindowManager(21711): 	at de.tap.easy_xkcd.Activities.MainActivity.onStart(MainActivity.java:758)
E/AndroidRuntime(21711): Process: de.tap.easy_xkcd, PID: 21711
E/AndroidRuntime(21711): java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.design.widget.FloatingActionButton de.tap.easy_xkcd.Activities.MainActivity.getFab()' on a null object reference
E/AndroidRuntime(21711): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment.onPrepareOptionsMenu(ComicFragment.java:572)
W/ActivityManager(  619):   Force finishing activity de.tap.easy_xkcd/.Activities.MainActivity
I/WindowManager(  619): Screen frozen for +813ms due to Window{488f8e7 u0 Starting de.tap.easy_xkcd}
I/WindowManager(  619): Screenshot max retries 4 of Token{b6b2bce ActivityRecord{ad408c9 u0 de.tap.easy_xkcd/.Activities.MainActivity t5032 f}} appWin=Window{8560a8a u0 Lade Comics…} drawState=1
W/ActivityManager(  619): Activity pause timeout for ActivityRecord{ad408c9 u0 de.tap.easy_xkcd/.Activities.MainActivity t5032 f}
D/Launcher( 2023): bindAppWidget: id=22 belongs to component ComponentInfo{de.tap.easy_xkcd/de.tap.easy_xkcd.widget.WidgetLatestProvider}
I/WindowState(  619): WIN DEATH: Window{e924556 u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}
I/ActivityManager(  619): Process de.tap.easy_xkcd (pid 21711) has died
D/Launcher( 2023): bindAppWidget: id=22 belongs to component ComponentInfo{de.tap.easy_xkcd/de.tap.easy_xkcd.widget.WidgetLatestProvider}

```

**Comment by T-Rex96** [comment]
Sorry I've been pretty busy lately, I'll probably have time to fix the crash this weekend

**Comment by rugk** [comment]
So even with version this happens again:

```
E/AndroidRuntime( 6022): Process: de.tap.easy_xkcd, PID: 6022
E/AndroidRuntime( 6022): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment$ComicAdapter.<init>(ComicFragment.java:134)
E/AndroidRuntime( 6022): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$ComicBrowserPagerAdapter.<init>(ComicBrowserFragment.java:193)
E/AndroidRuntime( 6022): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPostExecute(ComicBrowserFragment.java:167)
E/AndroidRuntime( 6022): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPostExecute(ComicBrowserFragment.java:125)
E/AndroidRuntime( 6326): Process: de.tap.easy_xkcd, PID: 6326
E/AndroidRuntime( 6326): java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.design.widget.FloatingActionButton de.tap.easy_xkcd.Activities.MainActivity.getFab()' on a null object reference
E/AndroidRuntime( 6326): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment.onPrepareOptionsMenu(ComicFragment.java:573)
I/ActivityManager(  615): Start proc 25350:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  615): Process de.tap.easy_xkcd (pid 25350) has died
I/ActivityManager(  615): Start proc 3834:de.tap.easy_xkcd/u0a248 for broadcast de.tap.easy_xkcd/.widget.WidgetLatestProvider
I/ActivityManager(  615): Killing 3834:de.tap.easy_xkcd/u0a248 (adj 15): empty #17
I/ActivityManager(  615): START u0 {act=de.tap.easy_xkcd.ACTION_COMIC flg=0x10000000 cmp=de.tap.easy_xkcd/.Activities.MainActivity bnds=[36,200][1044,1203] (has extras)} from uid 10248 on display 0
I/ActivityManager(  615): Start proc 13359:de.tap.easy_xkcd/u0a248 for activity de.tap.easy_xkcd/.Activities.MainActivity
W/XPrivacy(13359): Hooking package=de.tap.easy_xkcd
I/ActivityManager(  615): Displayed de.tap.easy_xkcd/.Activities.MainActivity: +1s797ms
E/AndroidRuntime(13359): Process: de.tap.easy_xkcd, PID: 13359
E/AndroidRuntime(13359): java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.design.widget.FloatingActionButton de.tap.easy_xkcd.Activities.MainActivity.getFab()' on a null object reference
E/AndroidRuntime(13359): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment.onPrepareOptionsMenu(ComicFragment.java:573)
I/WindowManager(  615): Screen frozen for +436ms due to AppWindowToken{496653d token=Token{c6ceac9 ActivityRecord{837cad0 u0 de.tap.easy_xkcd/.Activities.MainActivity t6271}}}
W/ActivityManager(  615):   Force finishing activity de.tap.easy_xkcd/.Activities.MainActivity
W/ActivityManager(  615): Activity pause timeout for ActivityRecord{837cad0 u0 de.tap.easy_xkcd/.Activities.MainActivity t6271 f}
I/WindowState(  615): WIN DEATH: Window{fd95bd7 u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}
D/Launcher( 2039): bindAppWidget: id=22 belongs to component ComponentInfo{de.tap.easy_xkcd/de.tap.easy_xkcd.widget.WidgetLatestProvider}
I/ActivityManager(  615): Process de.tap.easy_xkcd (pid 13359) has died
D/Launcher( 2039): bindAppWidget: id=22 belongs to component ComponentInfo{de.tap.easy_xkcd/de.tap.easy_xkcd.widget.WidgetLatestProvider}
```

**Comment by T-Rex96** [comment]
Still can't reproduce on my device, so I can only guess...
Let's see if I fixed it this time
